source 'http://rubygems.org'

gem 'cucumber', '2.3.3'
gem 'rspec'
gem 'selenium-webdriver'
gem 'watir-webdriver'
gem 'require_all'
gem 'activesupport', '4.1.8'
gem 'rake'
gem 'simplecov'
gem 'simplecov-rcov'
gem 'rautomation'
#gem 'pretty_face'

# gem to connect to saucelabs and also dynamically change browser parameters
gem 'saucelabs'

gem 'rubyXL'
gem 'rubyzip'
gem 'activerecord'
gem 'nokogiri'

#gem 'sqlite3'




#gem 'cucumber' , '1.3.19'










